//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSystem.Resources.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMDatabaseEntities : DbContext
    {
        public EMDatabaseEntities()
            : base("name=EMDatabaseEntities")
        {
        }
        private static EMDatabaseEntities context;

        public static EMDatabaseEntities GetContext()
        {
            if (context == null)
                context = new EMDatabaseEntities();

            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiary> Beneficiary { get; set; }
        public virtual DbSet<BeneficiaryType> BeneficiaryType { get; set; }
        public virtual DbSet<Certificate> Certificate { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<CountStudents> CountStudents { get; set; }
    }
}
