//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSystem.Resources.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CertificateId { get; set; }
        public int ClassesId { get; set; }
        public int TypeId { get; set; }
        public string Patronymic { get; set; }
    
        public virtual BeneficiaryType BeneficiaryType { get; set; }
        public virtual Certificate Certificate { get; set; }
        public virtual Classes Classes { get; set; }
    }
}
