//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSystem.Resources.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountStudents
    {
        public int ClassId { get; set; }
        public int ManyChildren { get; set; }
        public int LowIncome { get; set; }
        public int Invalid { get; set; }
        public int Orphan { get; set; }
        public int OVZ { get; set; }
        public int InHomeOVZ { get; set; }
        public int InHomeInvalid { get; set; }
        public int InHomeNoStatus { get; set; }
        public int InFeedingParents { get; set; }
        public int NoType { get; set; }
        public int AllStudents { get; set; }
    
        public virtual Classes Classes { get; set; }
    }
}
